version: '3'

services:
  postgres-compose:
    image: postgres:10.3-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "product"
    ports:
      - "5432:5432"
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
    networks:
      - commons-api

  pgadmin-compose:
    image: dpage/pgadmin4

    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@email.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "15432:80"
    depends_on:
      - postgres-compose
    networks:
      - commons-api

networks:
  commons-api:
    driver: bridge